### ISSUE TITLE
Can't downlaod Generator or Comparator

### ISSUE THREAD

**Issue by LeadHail** [GoodAI/space-engineers-ai-spaceship-generator#10]
![image](https://user-images.githubusercontent.com/39394418/201240324-ca1adc18-c8a1-4937-87a6-440ba5a0918e.png)

I can't download either of the .exe's saying that i don't have the correct permissions from the website owner.

**Comment by gallorob** [comment]
@LeadHail what browser are you using? I don't think it's an issue with our repository settings however, but we can look into it.

**Comment by gallorob** [comment]
@LeadHail great, thank you.

Looking at this error message on Chrome, it looks like it's either due to a misconfiguration on the website, or some settings on the browser. Seeing as other people can download the executable with Chrome (myself included, using version 107.0.5304.107), I believe it may be an issue with your Chrome browser.

Can you try downloading the executables with a different browser (Edge, Firefox, etc...)? If it fails even with those, it may be an antivirus setting.

@martinpoliak-goodai are you aware of possible causes for this kind of problems? If it's common enough, it may be worth it to add a disclaimer on the readme so that users don't have to open issues about it.

**Comment by LeadHail** [comment]
I was able to download it off of my Server Computer just fine, could've been antimalware issue.

**Comment by gallorob** [comment]
Great, I'm going to close this issue for now then.
