### ISSUE TITLE
Ships are generated on there side.

### ISSUE THREAD

**Issue by Droid-B1045** [GoodAI/space-engineers-ai-spaceship-generator#15]
*Issue type:* [ bug ]

*Severity:*  [ low ] but very irritating!

**Describe the issue**
Ships are generated on there side and i cant turn the camera to look at them from the top down.

**To Reproduce**
Generate a ship and look at its front to see where the cockpit is

**Expected behavior**
I expect to see them from the top or front and get really confused when i realise the cool ship i generated has its interiors in the wrong direction.

**Screenshots**
![image](https://user-images.githubusercontent.com/119160801/204129580-516faa3a-c978-4769-90be-e7b094dd9e2e.png)
![image](https://user-images.githubusercontent.com/119160801/204129663-fe95755a-0b5f-4121-8600-287c3eb21598.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome]
 - Spaceship.Generator.v1.0.3.exe

**Comment by gallorob** [comment]
Hi @Droid-B1045, this seems similar to a [previous issue](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/issues/8) that I resolved, so I'm surprised you're running into it again.

I'm checking various spaceships and they all seem aligned correctly to me:
![immagine](https://user-images.githubusercontent.com/32876132/204284705-0146c4d6-a4b8-4375-8683-f404b1c07a95.png)

In order to find the issue, can you please:

- double check that you're running v1.0.3 (as it's the version that contains the alignment fix)
- let me know if this appears after a certain iteration or is already present in the initial population
- if possible, download the spaceship and upload the .zip file here, attaching it to a comment

These would help me tremendously, thank you.

**Comment by gallorob** [comment]
@Droid-B1045 thank you for checking! Are you running the user study mode or the user mode (ie: have you accepted the privacy policy or declined it)?

**Comment by gallorob** [comment]
Seems like there was a line missing in the source, fixed and will be released once https://github.com/GoodAI/space-engineers-ai-spaceship-generator/pull/18 is approved.
