### ISSUE TITLE
Comparator Program doesn't open

### ISSUE THREAD

**Issue by EB-Razy** [GoodAI/space-engineers-ai-spaceship-generator#7]
I have finally succeeded in taking the user study after 4 attempts. My issue now is that the Comparator program doesn't open.
It loads the log screen and logo then closes fast. I was able to screenshot the message for the fraction of a second it was up.
I have tried running as an admin and re-downloading the file.
I have also tried downloading the binaries and unzipping in case that helped, but didn't.
Any advice?
![Comaparator error](https://user-images.githubusercontent.com/116943870/198830290-0e2adf5e-a35f-4b3d-8ffc-7cc92ecd40af.png)

**Comment by gallorob** [comment]
Hi @EB-Razy, thanks for participating in the user study! This issue has already been raised (https://github.com/GoodAI/space-engineers-ai-spaceship-generator/issues/2) and will be fixed with the next release. If possible, you can launch the application from source (`python comparator_webapp_launcher.py`), that still works even without the fix. Otherwise please wait for the next release.

I will reopen the previous issue and close this one so other people won't have trouble finding it.

PS: in the future, If you find any other issue with the system, please follow the issue template 😉
