### ISSUE TITLE
The spaceship preview isn't aligned

### ISSUE THREAD

**Issue by Timberhouse** [GoodAI/space-engineers-ai-spaceship-generator#8]
*Issue type:* Choose from [ bug | feature request ]
Bug

*Severity:* Suggest one from [low | medium | high (application-breaking) ]
low

**Describe the issue**
The spaceship preview isn't aligned with the tileset.
Also downloaded blueprints with grid orientation in Space Engineers.

**To Reproduce**
It can always be seen in the spaceship preview.

**Expected behavior**
The orientation of the generated spacecraft is incorrect.

**Screenshots**
If applicable, please add screenshots to help explain your problem, they tremendously help understanding the issue.
![WS001343](https://user-images.githubusercontent.com/10172989/199490142-eddf25b7-4510-43a4-ac76-fac1330f6610.JPG)
![WS001344](https://user-images.githubusercontent.com/10172989/199490226-47567c50-abba-497a-83b2-95c3224e759f.JPG)
![20221102214235_1](https://user-images.githubusercontent.com/10172989/199492544-ef64b87c-9632-48aa-be36-0688f9d587ef.jpg)
The red plane is vertical align.

**Log file**
In case of bugs, please upload the relevant log file (log_{TIMESTAMP}.log) for inspection. The log file does not contain any user information if the user declined the privacy policy or have already completed the user study.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 22H2
 - Browser: Chrome 106.0.5249.119
 - .exe file name: AI.Spaceship.Generator.v1.0.2.exe

**Additional context**

**Comment by gallorob** [comment]
Hi @Timberhouse, thank you for creating this issue!

I gave priority to the other issues first, but I have now pushed the change https://github.com/arayabrain/space-engineers-ai-spaceship-generator/commit/a7c913a5ca025685ef6b0427f709afb6dca7d277 to set a rotation to the entire spaceship in the preview so that it's aligned to the in-game orientation of the tileset. See below:
![immagine](https://user-images.githubusercontent.com/32876132/201671490-5aeba695-d2f4-4691-b198-e6fbd1c668d8.png)

This will be included in the next release, so I will close the issue.
